# Generated by Django 5.2.5 on 2025-08-18 12:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='隊伍名稱')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='隊伍Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='遊戲內暱稱')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.team', verbose_name='所屬隊伍')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='賽事名稱')),
                ('game', models.CharField(max_length=100, verbose_name='遊戲名稱')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='報名開始日期')),
                ('end_date', models.DateTimeField(verbose_name='賽事結束日期')),
                ('rules', models.TextField(verbose_name='賽事規章')),
                ('status', models.CharField(choices=[('upcoming', '尚未開始'), ('ongoing', '進行中'), ('finished', '已結束')], default='upcoming', max_length=10, verbose_name='賽事狀態')),
                ('participants', models.ManyToManyField(blank=True, related_name='tournaments', to='tournaments.team', verbose_name='參賽隊伍')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='比賽輪次')),
                ('team1_score', models.PositiveIntegerField(default=0, verbose_name='隊伍一得分')),
                ('team2_score', models.PositiveIntegerField(default=0, verbose_name='隊伍二得分')),
                ('match_time', models.DateTimeField(blank=True, null=True, verbose_name='預計比賽時間')),
                ('status', models.CharField(choices=[('scheduled', '尚未開始'), ('completed', '已結束')], default='scheduled', max_length=10, verbose_name='比賽狀態')),
                ('team1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team1', to='tournaments.team', verbose_name='隊伍一')),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team2', to='tournaments.team', verbose_name='隊伍二')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournaments.team', verbose_name='勝者')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament', verbose_name='所屬賽事')),
            ],
        ),
    ]
