# Generated by Django 5.2.5 on 2025-09-24 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_number', models.PositiveIntegerField(verbose_name='地圖編號')),
                ('map_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='地圖名稱')),
                ('team1_score', models.PositiveIntegerField(default=0, verbose_name='隊伍一地圖得分')),
                ('team2_score', models.PositiveIntegerField(default=0, verbose_name='隊伍二地圖得分')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tournaments.match', verbose_name='所屬比賽')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='tournaments.team', verbose_name='地圖勝者')),
            ],
            options={
                'ordering': ['map_number'],
                'unique_together': {('match', 'map_number')},
            },
        ),
        migrations.CreateModel(
            name='PlayerGameStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.PositiveIntegerField(default=0, verbose_name='擊殺')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='死亡')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='助攻')),
                ('first_kills', models.PositiveIntegerField(default=0, verbose_name='首殺')),
                ('acs', models.FloatField(default=0.0, verbose_name='ACS')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='tournaments.game', verbose_name='對應小局')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='tournaments.player', verbose_name='選手')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.team', verbose_name='代表隊伍')),
            ],
            options={
                'verbose_name': '選手單局數據',
                'verbose_name_plural': '選手單局數據',
                'unique_together': {('game', 'player')},
            },
        ),
        migrations.DeleteModel(
            name='PlayerMatchStat',
        ),
    ]
