# Generated by Django 5.2.5 on 2025-08-18 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_lower_bracket',
            field=models.BooleanField(default=False, verbose_name='是否為敗部賽'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('single_elimination', '單敗淘汰'), ('double_elimination', '雙敗淘汰'), ('round_robin', '分組循環'), ('swiss', '瑞士輪')], default='single_elimination', max_length=20, verbose_name='賽制'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='組別名稱')),
                ('teams', models.ManyToManyField(related_name='tournament_groups', to='tournaments.team', verbose_name='組內隊伍')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournament', verbose_name='所屬賽事')),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='勝場')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='敗場')),
                ('draws', models.PositiveIntegerField(default=0, verbose_name='平局')),
                ('points', models.IntegerField(default=0, verbose_name='積分')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.group', verbose_name='所屬分組')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.team', verbose_name='隊伍')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournament', verbose_name='所屬賽事')),
            ],
            options={
                'unique_together': {('tournament', 'team')},
            },
        ),
    ]
