# Generated by Django 5.2.5 on 2025-09-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_game_playergamestat_delete_playermatchstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='map',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地圖'),
        ),
    ]
