# Generated by Django 5.2.5 on 2025-08-18 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_match_is_lower_bracket_tournament_format_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.PositiveIntegerField(default=0, verbose_name='擊殺')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='死亡')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='助攻')),
                ('first_kills', models.PositiveIntegerField(default=0, verbose_name='首殺')),
                ('acs', models.FloatField(default=0.0, verbose_name='ACS')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='tournaments.match', verbose_name='對應比賽')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='tournaments.player', verbose_name='選手')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.team', verbose_name='代表隊伍')),
            ],
            options={
                'verbose_name': '選手比賽數據',
                'verbose_name_plural': '選手比賽數據',
                'unique_together': {('match', 'player')},
            },
        ),
    ]
