# Generated by Django 5.2.8 on 2025-11-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_match_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_teams',
            field=models.PositiveIntegerField(default=8, verbose_name='最大隊伍數'),
        ),
        migrations.AddField(
            model_name='team',
            name='school',
            field=models.CharField(blank=True, max_length=200, verbose_name='學校名稱'),
        ),
    ]
