# Generated by Django 5.2.5 on 2025-09-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_playermatchstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='player_avatars/', verbose_name='選手頭像'),
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Duelist', '決鬥者'), ('Initiator', '先鋒'), ('Controller', '煙位'), ('Sentinel', '守衛'), ('Flex', '彈性位')], default='Flex', max_length=20, verbose_name='角色定位'),
        ),
    ]
